spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: hits
    password: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8191