spring:
  flyway:
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/codehedgehog
    user: qwerty
    password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/codehedgehog
    username: qwerty
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8191