spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codehedgehog
    username: qwerty
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8191